databases:
  - name: postgres
    databaseName: jaizglobal
    user: jaizglobal
    ipAllowList: []
    plan: free


services:
  - type: web
    name: jaizglobal
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: true

    # -type: redis
    #  name: redis
    #  ipAllowList: []
    #  plan: free
    #  maxmemoryPolicy: noeviction
