databases:
  - name: postgres
    databaseName: jaizglobal
    user: jaizglobal
    ipAllowList: []
    plan: free


services:
  - type: web
    name: jaizglobal
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
        - key: AWS_REGION # Imported from Heroku app
          value: us-east-2
        - key: AWS_ACCESS_KEY_ID
           value: <%= ENV['AWS_ACCESS_KEY_ID'] %> # Imported from Heroku app
        - key: AWS_SECRET_ACCESS_KEY
          value: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>

        - key: LANG # Imported from Heroku app
          value: en_US.UTF-8
        - key: RACK_ENV # Imported from Heroku app
          value: production
        - key: RAILS_ENV # Imported from Heroku app
          value: production
        - key: RAILS_LOG_TO_STDOUT # Imported from Heroku app
          value: enabled
        - key: RAILS_SERVE_STATIC_FILES # Imported from Heroku app
          value: enabled
        - key: S3_BUCKET_NAME # Imported from Heroku app
          value: homestoragebox

    # -type: redis
    #  name: redis
    #  ipAllowList: []
    #  plan: free
    #  maxmemoryPolicy: noeviction
